tosca_definitions_version: cloudify_dsl_1_4

imports:
  - https://cloudify.co/spec/cloudify/6.4.0/types.yaml
  - plugin:cloudify-docker-plugin

inputs:

  image_tag:
    description: Tag for the image to build
    type: string
    default: "ansible_local:0.1"

dsl_definitions:

  docker_config: &docker_config
    docker_sock_file: /var/run/docker.sock

node_templates:


  docker_ansible_container:
    type: cloudify.nodes.docker.container
    properties:
      client_config: *docker_config
      resource_config:
        image_tag: {get_input: image_tag }
        container_args:
          command: 'ansible-playbook -i hosts create.yaml'
          working_dir: '/'
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
            ANSIBLE_INVALID_TASK_ATTRIBUTE_FAILED: False
    interfaces:
      cloudify.interfaces.lifecycle:
        stop:
          implementation: docker.cloudify_docker.tasks.stop_container
          inputs:
            stop_command: 'ansible-playbook -i hosts delete.yaml'