---
- name: Start Calico resources
  kube:
    name: "{{item.item.name}}"
    namespace: "kube-system"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "{{item.item.type}}"
    filename: "{{kube_config_dir}}/{{item.item.file}}"
    state: "latest"
  with_items:
    - "{{ calico_node_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0] and not item is skipped
  loop_control:
    label: "{{ item.item.file }}"

- name: "calico upgrade complete"
  shell: "{{ bin_dir }}/calico-upgrade complete --no-prompts --apiconfigv1 /etc/calico/etcdv2.yml --apiconfigv3 /etc/calico/etcdv3.yml"
  when:
    - inventory_hostname == groups['kube-master'][0]
    - calico_upgrade_enabled|default(True)
    - calico_upgrade_needed|default(False)
