---
dependencies:
  - role: kubernetes-apps/ingress_controller/ingress_nginx
    when: ingress_nginx_enabled
    tags:
      - apps
      - ingress-nginx
      - ingress-controller

  - role: kubernetes-apps/ingress_controller/cert_manager
    when: cert_manager_enabled
    tags:
      - apps
      - cert-manager
      - ingress-controller
