---
# Log-level
cilium_debug: false
cilium_disable_ipv4: false

# Etcd SSL dirs
cilium_cert_dir: /etc/cilium/certs

# Cilium Network Policy directory
cilium_policy_dir: /etc/kubernetes/policy

# Limits for apps
cilium_memory_limit: 500M
cilium_cpu_limit: 500m
cilium_memory_requests: 64M
cilium_cpu_requests: 100m

# Optional features
cilium_enable_prometheus: false
