tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/4.5.5/types.yaml
  - plugin:cloudify-openstack-plugin
  - plugin:cloudify-utilities-plugin

inputs:

  region_name:
    type: string

  public_subnet_cidr:
    type: string
    default: 10.10.1.0/24

  agent_user:
    type: string
    default: centos

  image_id:
    type: string

  flavor_id:
    type: string

  resource_name_prefix:
    type: string

dsl_definitions:

  client_config: &client_config
    auth_url: { get_secret: auth_url }
    username: { get_secret: username }
    password: { get_secret: password }
    project_name: { get_secret: project_name }
    region_name: { get_secret: region_name }

node_templates:

  host:
    type: cloudify.nodes.openstack.Server
    properties:
      client_config: *client_config
      agent_config:
        install_method: none
        key: { get_secret: agent_key_private }
        user: { get_input: agent_user }
      use_public_ip: true
      resource_config:
        name: { concat: [ { get_input: resource_name_prefix }, '-infra-host' ] }
        image_id: { get_input: image_id }
        flavor_id: { get_input: flavor_id }
        user_data: { get_attribute: [ cloud_init, cloud_config ] }
    relationships:
      - type: cloudify.relationships.openstack.server_connected_to_port
        target: nic
      - type: cloudify.relationships.depends_on
        target: ip
      - type: cloudify.relationships.depends_on
        target: cloud_init

  ip:
    type: cloudify.nodes.openstack.FloatingIP
    properties:
      client_config: *client_config
    relationships:
      - type: cloudify.relationships.connected_to
        target: external_network
      - type: cloudify.relationships.connected_to
        target: nic

  nic:
    type: cloudify.nodes.openstack.Port
    properties:
      client_config: *client_config
      resource_config:
        network_id: { get_attribute: [ network, id ] }
    relationships:
      - type: cloudify.relationships.connected_to
        target: subnet
      - type: cloudify.relationships.connected_to
        target: security_group

  security_group:
    type: cloudify.nodes.openstack.SecurityGroup
    properties:
      client_config: *client_config
      resource_config:
        name: { concat: [ { get_input: resource_name_prefix }, '-infra-group' ] }
        description: 'db lb app infra group'
      security_group_rules:
        - direction: ingress
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - direction: ingress
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - direction: ingress
          protocol: tcp
          port_range_min: 3306
          port_range_max: 3306
        - direction: ingress
          protocol: tcp
          port_range_min: 4444
          port_range_max: 4444
        - direction: ingress
          protocol: tcp
          port_range_min: 4567
          port_range_max: 4568

  subnet:
    type: cloudify.nodes.openstack.Subnet
    properties:
      client_config: *client_config
      use_external_resource: true
      resource_config:
        id: { get_capability: [ openstack, public_subnet ] }
    relationships:
      - type: cloudify.relationships.contained_in
        target: network
      - type: cloudify.relationships.openstack.subnet_connected_to_router
        target: router

  network:
    type: cloudify.nodes.openstack.Network
    properties:
      client_config: *client_config
      use_external_resource: true
      resource_config:
        id: { get_capability: [ openstack, public_network ] }

  router:
    type: cloudify.nodes.openstack.Router
    properties:
      client_config: *client_config
      use_external_resource: true
      resource_config:
        id: { get_capability: [ openstack, public_network_router ] }
    relationships:
      - type: cloudify.relationships.connected_to
        target: external_network

  external_network:
    type: cloudify.nodes.openstack.Network
    properties:
      client_config: *client_config
      use_external_resource: true
      resource_config:
        id: { get_capability: [ openstack, external_network ] }
        kwargs:
          routing:
            external: true

  cloud_init:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
        - name: { get_input: agent_user }
          primary-group: wheel
          shell: /bin/bash
          sudo: ['ALL=(ALL) NOPASSWD:ALL']
          ssh-authorized-keys:
          - { get_secret: agent_key_public }

groups:

  scalable_compute:
    members:
      - host
      - nic
      - ip

capabilities:

  ip:
    description: Host IP
    value: { get_attribute: [ host, ip ] }
