---
- name: Flannel pre-upgrade | Purge legacy flannel systemd unit file
  file:
    path: "/etc/systemd/system/docker.service.d/flannel-options.conf"
    state: absent
  notify:
    - Flannel | delete default docker bridge

- name: Flannel pre-upgrade | Purge legacy Flannel static pod manifest
  file:
    path: "{{ kube_manifest_dir }}/flannel-pod.manifest"
    state: absent
  notify:
    - Flannel | delete flannel interface

- name: Flannel pre-upgrade | Remove Flannel's certificate directory not required by CNI
  file:
    dest: "{{ flannel_cert_dir }}"
    state: absent
