images_dir: /images/base

docker_user: kubespray+buildvmimages
docker_host: quay.io
registry: quay.io/kubespray

images:
    ubuntu-1604:
      filename: xenial-server-cloudimg-amd64-disk1.img
      url: https://storage.googleapis.com/kubespray-images/ubuntu/xenial-server-cloudimg-amd64-disk1.img
      checksum: sha256:c0d099383cd064390b568e20d1c39a9c68ba864764404b70f754a7b1b2f808f7
      converted: false

    ubuntu-1804:
      filename: bionic-server-cloudimg-amd64.img
      url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
      checksum: sha256:c3d0e03f4245ffaabd7647e6dabf346b944a62b9934d0a89f3a04b4236386af2
      converted: false

    fedora-28:
      filename: Fedora-Cloud-Base-28-1.1.x86_64.qcow2
      url: https://mirror.netsite.dk/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
      checksum: sha256:d987209719fadaf81b8bff85c5d3590a1d3dac6357e4838fde8357086c49b5b4
      converted: true

    centos-7:
      filename: CentOS-7-x86_64-GenericCloud-1809.qcow2
      url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1809.qcow2
      checksum: sha256:42c062df8a8c36991ec0282009dd52ac488461a3f7ee114fc21a765bfc2671c2
      converted: true

    debian-9:
      filename: debian-9-openstack-amd64.qcow2
      url: https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
      checksum: sha256:01d9345ba7a6523d214d2eaabe07fe7b4b69b28e63d7a6b322521e99e5768719
      converted: true
