tosca_definitions_version: cloudify_dsl_1_3

description: Install Kubernetes on kube-master and kube-node.

imports:
  - plugin:cloudify-ansible-plugin

inputs:

  kubespray_ansible_playbook_path:
    type: string
    default: kubespray/cluster.yml

  kubespray_ansible_playbook_path_removal:
    type: string
    default: kubespray/remove-node.yml

  kubespray_dns_mode:
    type: string
    default: kubedns

  kubespray_kube_network_plugin:
    type: string
    default: flannel

node_templates:

  kube-base-config:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: ansible.cloudify_ansible.tasks.run
          inputs:
            site_yaml_path: { get_input: kubespray_ansible_playbook_path }
            run_data:
              dns_mode: { get_input: kubespray_dns_mode}
              kube_network_plugin: { get_input: kubespray_kube_network_plugin }
              kube_api_anonymous_auth: true
            options_config:
              skip_tags:
                - localhost
                - check
                - bastion
              ssh_common_args: '-o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null'
    relationships:
      - type: cloudify.ansible.relationships.connected_to_host
        target: kube-master
      - type: cloudify.ansible.relationships.connected_to_host
        target: kube-node

groups:

  k8s-cluster:
    members:
    - kube-master
    - kube-node

  etcd:
    members:
    - kube-master
