tosca_definitions_version: cloudify_dsl_1_3

imports:
  - plugin:cloudify-utilities-plugin

node_templates:

  cloudify-host-cloud-config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        groups:
        - docker
        users:
          - name: { get_input: agent_user }
            primary-group: { get_input: agent_user }
            groups: docker, wheel, root
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: agent_key_public }
        runcmd:
        - "yum install python-netaddr"
