---
dependencies:
  - role: policy_controller/calico
    when:
      - kube_network_plugin == 'calico'
      - enable_network_policy
    tags:
      - policy-controller

  - role: policy_controller/calico
    when:
      - kube_network_plugin == 'canal'
    tags:
      - policy-controller
