---
- name: Install rkt
  import_tasks: install.yml
  when: not ansible_os_family in ["CoreOS", "Container Linux by CoreOS"]

- name: Set up cron job to do garbage cleanup
  copy:
    src: rkt-gc.sh
    dest: /etc/cron.hourly/rkt-gc.sh
    owner: root
    group: root
    mode: 0750
  when: not ansible_os_family in ["CoreOS", "Container Linux by CoreOS"]
