---
- name: Uncordon node
  command: "{{ bin_dir }}/kubectl --kubeconfig /etc/kubernetes/admin.conf uncordon {{ inventory_hostname }}"
  delegate_to: "{{ groups['kube-master'][0] }}"
  when:
    - needs_cordoning|default(false)
