---
dependencies:
  - role: network_plugin/cilium
    when: kube_network_plugin == 'cilium'
    tags:
      - cilium

  - role: network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico

  - role: network_plugin/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel

  - role: network_plugin/weave
    when: kube_network_plugin == 'weave'
    tags:
      - weave

  - role: network_plugin/canal
    when: kube_network_plugin == 'canal'
    tags:
      - canal

  - role: network_plugin/contiv
    when: kube_network_plugin == 'contiv'
    tags:
      - contiv

  - role: network_plugin/kube-router
    when: kube_network_plugin == 'kube-router'
    tags:
      - kube-router

  - role: network_plugin/cloud
    when: kube_network_plugin == 'cloud'

  - role: network_plugin/multus
    when: kube_network_plugin_multus
    tags:
      - multus
