---
docker_kernel_min_version: '0'

# overide defaults, missing 17.03 for aarch64
docker_version: '1.13'

# http://mirror.centos.org/altarch/7/extras/aarch64/Packages/
# or do 'yum --showduplicates list docker'
docker_versioned_pkg:
  'latest': docker
  '1.12': docker-1.12.6-48.git0fdc778.el7
  '1.13': docker-1.13.1-63.git94f4240.el7

# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# http://mirror.centos.org/altarch/7/extras/aarch64/Packages/

docker_package_info:
  pkg_mgr: yum
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
