---

- name: Delete node
  command: "{{ bin_dir}}/kubectl delete node {{ item }}"
  with_items:
    - "{{ node.split(',') | default(groups['kube-node']) }}"
  delegate_to: "{{ groups['kube-master']|first }}"
  run_once: true
  ignore_errors: yes
