---
- import_tasks: check.yml

- import_tasks: pre.yml

- import_tasks: upgrade.yml
  when:
    - calico_upgrade_enabled
    - calico_upgrade_needed
  run_once: yes
  delegate_to: "{{ groups['kube-master'][0] }}"

- include_tasks: install.yml
