---
dependencies:
  - role: container-engine/cri-o
    when:
      - container_manager == 'crio'
    tags:
      - container-engine
      - crio

  - role: container-engine/rkt
    when:
      - container_manager == 'rkt'
    tags:
      - container-engine
      - rkt

  - role: container-engine/docker
    when:
      - container_manager == 'docker' or container_manager == "rkt"
    tags:
      - container-engine
      - docker
      - rkt
