---
# Existing search/nameserver resolvconf entries will be purged and
# ensured by this additional data:

# Max of 4 names is allowed and no more than 256 - 17 chars total
# (a 2 is reserved for the 'default.svc.' and'svc.')
# searchdomains:
#   - foo.bar.lc

# Max of 2 is allowed here (a 1 is reserved for the dns_server)
# nameservers:
#   - 127.0.0.1

# Versions
dnsmasq_version: 2.72

# Images
dnsmasq_image_repo: "andyshinn/dnsmasq"
dnsmasq_image_tag: "{{ dnsmasq_version }}"

# Limits for dnsmasq/kubedns apps
dns_cpu_limit: 100m
dns_memory_limit: 170Mi
dns_cpu_requests: 40m
dns_memory_requests: 50Mi

# Autoscaler parameters
dnsmasq_nodes_per_replica: 10
dnsmasq_min_replicas: 1

# Custom name servers
dnsmasq_upstream_dns_servers: []

# Try each query with each server strictly in the order
dnsmasq_enable_strict_order: true

# Send queries to all servers
dnsmasq_enable_all_servers: false

# Maximum number of concurrent DNS queries.
dns_forward_max: 150

# Caching params
cache_size: 1000
dnsmasq_max_cache_ttl: 10
dnsmasq_enable_no_negcache: true

# Maximum TTL value that will be handed out to clients.
# The specified maximum TTL will be given to clients
# instead of the true TTL value if it is lower.
dnsmasq_max_ttl: 20

# If enabled - don't read /etc/resolv.conf.
dnsmasq_enable_no_resolv: true

# Bogus private reverse lookups.
# All reverse lookups for private IP ranges (ie 192.168.x.x, etc)
# which are not found in /etc/hosts or the DHCP leases file are
# answered with "no such domain" rather than being forwarded upstream.
# The set of prefixes affected is the list given in RFC6303, for IPv4 and IPv6.
dnsmasq_enable_bogus_priv: true

# This option forces dnsmasq to really bind only the interfaces it is listening on
dnsmasq_enable_bind_interfaces: true
dnsmasq_listen_address: "0.0.0.0"

# Additional hosts file or directory
dnsmasq_addn_hosts: /etc/hosts

# Facility to which dnsmasq will send syslog entries.
# If the facility is '-' then dnsmasq logs to stderr.
dnsmasq_log_facility: "-"

# Additional startup parameters
dnsmasq_additional_startup_parameters: []
