---
# discovery_timeout modifies the discovery timeout
discovery_timeout: 5m0s
# Optionally remove kube_proxy installed by kubeadm
kube_proxy_remove: false

# If non-empty, will use this string as identification instead of the actual hostname
kube_override_hostname: >-
  {%- if cloud_provider is defined and cloud_provider in [ 'aws' ] -%}
  {%- else -%}
  {{ inventory_hostname }}
  {%- endif -%}
