tosca_definitions_version: cloudify_dsl_1_5

description: This blueprint installs Docker on some VM at IP or hostname docker_host.

imports:
  - cloudify/types/types.yaml
  - plugin:cloudify-docker-plugin

inputs:

  docker_host:
    type: string
    required: true

  docker_user:
    type: string
    required: true

dsl_definitions:

  docker_machine_config: &docker_machine_config
    docker_ip: { get_input: docker_host }
    docker_user: { get_input: docker_user }
    docker_key: { get_secret: agent_key_private }

node_templates:

  docker_installation:
    type: cloudify.nodes.docker.host
    properties:
      docker_machine: *docker_machine_config
